name: PulseView macOS build for ARM

on:
  workflow_dispatch:

env:
  # The path where the compiled packages will be installed.
  INSTALL_DIR: "${{ github.workspace }}/sr"
  # Git URL for the libserialport dependency
  LIBSERIALPORT_REPO: "git://sigrok.org/libserialport"
  # Git URL for the libsigrok dependency
  LIBSIGROK_REPO: "git://sigrok.org/libsigrok"
  # Git branch for the libsigrok dependency
  LIBSIGROK_BRANCH: "master"
  # Git URL for the libsigrokdecode dependency
  LIBSIGROKDECODE_REPO: "git://sigrok.org/libsigrokdecode"
  # Git URL for the sigrok-firmware dependency
  SIGROK_FIRMWARE_REPO: "git://sigrok.org/sigrok-firmware"
  # Git URL for the sigrok-firmware-fx2lafw dependency
  SIGROK_FIRMWARE_FX2LAFW_REPO: "git://sigrok.org/sigrok-firmware-fx2lafw"
  # Git URL for the sigrok-dumps dependency
  SIGROK_DUMPS_REPO: "git://sigrok.org/sigrok-dumps"
  # Misc commands
  WGET: "wget -c --quiet"
  GIT_CLONE: "git clone --depth=1"

defaults:
  run:
    shell: bash

jobs:
  
  build_pulseview_macos_arm:
    name: PulseView macOS build for ARM

    # See https://github.com/actions/runner-images/issues/9254
    runs-on: macos-latest

    env:
      TARGET: "arm"
      BREW_PYTHON_VERSION: "python@3"
      BREW_QT_VERSION: "qt"
      # Artifact infos
      ARTIFACT_TITLE: "pulseview"
      ARTIFACT_BIN_NAME: "pulseview"
      ARTIFACT_VERSION: "NIGHTLY"

    steps:
      - name: Install dependencies
        run: |
          brew install autoconf automake autoconf-archive pkg-config libtool \
          libzip libusb libftdi hidapi nettle check doxygen swig \
          glib glibmm@2.66 cmake boost sdcc gnu-sed $BREW_PYTHON_VERSION $BREW_QT_VERSION

      - name: Checkout sigrok-build
        # Cannot use actions/checkout because it always checks out the calling actions' repo, not the one specified
        run: |
          git clone https://github.com/${{ github.event.repository.owner }}/sigrok-build.git --depth 1

      - name: Build dependencies
        run: |
          cd sigrok-build/ci/macos
          source sigrok-macos-init-toolchain.sh
          ./sigrok-macos-build-dependencies.sh

      - name: Checkout sigrok's PulseView
        # Check out default PV repository unless we're processing a pull request
        uses: actions/checkout@v4
        with:
          # TODO: Clone from sigrok.org
          repository: sigrokproject/pulseview
          path: pulseview

      - name: Build PulseView
        run: |
          source sigrok-build/ci/macos/sigrok-macos-init-toolchain.sh
          cd pulseview
          git am ~/sigrok-build/0001-fix-build-with-QT-6.11.patch
          PKG_CONFIG_PATH=$P cmake -B build \
            -DCMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
            -DCMAKE_PREFIX_PATH=$(brew --prefix boost) \
            -DCMAKE_BUILD_TYPE=Debug \
            -DDISABLE_WERROR=FALSE \
            -DENABLE_TESTS=FALSE
          cmake --build build
          cmake --install

      - name: Build DMG
        run: |
          cd sigrok-build/ci/macos
          source sigrok-macos-init-toolchain.sh
          ./sigrok-macos-create-dmg.sh

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact-pulseview-arm-macos
          path: sigrok-build/ci/macos/pulseview*.dmg
